build fail demo

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -20,7 +20,9 @@ jobs:
         distribution: 'temurin'
         cache: maven
     - name: Build with Maven
-      run: mvn clean install -DskipTests
+      run: | 
+        mvn clean install -DskipTests
+        exit 1
   
   success_notify:
     needs: ['build']
@@ -30,5 +32,13 @@ jobs:
     steps:
       - name: Notify Success
         run: echo "Success email sent to the team"
+
+  failure_notify:
+    needs: ['build']
+    if: failure()
+    runs-on: ubuntu-latest
+    steps:
+      - name: Notify Failure
+        run: echo "Failure email sent to the team"
 
 
